name: CI
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          echo Installing dependencies...
          npm ci
          echo Running tests...
          npm run test
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Release
        run: |
          echo Installing dependencies...
          npm ci
          echo Release-it dry run...
          npm run release
